# Generated by Django 5.1.4 on 2024-12-24 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_soln_language_soln_posted_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soln',
            name='language',
        ),
        migrations.AlterField(
            model_name='soln',
            name='posted_by',
            field=models.CharField(max_length=100),
        ),
    ]
